### ISSUE TITLE
prolificURL vs. completionURL in magpie.config.js

### ISSUE THREAD

**Issue by brittaGrusdt** [magpie-ea/magpie-v3-docs#3]
Hi! While trying to deploy my experiment on Prolific, I found a small inconsistency in the documentation, see the attached screenshot. The text says 'prolificURL' but the example says 'completionUrl'. It would be great if you can clarify this section to avoid  any potential confusion, thank you!

![Screenshot 2022-04-26 at 09 15 37](https://user-images.githubusercontent.com/42784325/165243652-347df18c-3d30-49c9-acc0-c0707629aee9.png)

**Comment by marcelklehr** [comment]
Ah, nice catch. Thank you
