### ISSUE TITLE
socketUrl when hosting a local server (via Docker)

### ISSUE THREAD

**Issue by vini-macuch-silva** [magpie-ea/magpie-v3-docs#4]
Hi, it's me again,

So I was trying to collect some data using an experiment which submits the data to a server hosted locally via Docker (all working fine). While I am able to submit and retrieve data using directLink, the data submission is not working for my Prolific participants. I haven't been able to find anything in the documentation regarding the socketUrl in case of a local server, which I think might be my problem. I'm assuming that if I have `serverUrl: 'http://localhost:4000/'` my socketUrl would be `socketUrl: 'http://localhost:4000/socket'`. Is that correct? If not, any ideas what my issue might be? On the Prolific side it's all set up properly, with direct submission and participants being redirected back to Prolific directly.

Thank you!

**Comment by marcelklehr** [comment]
Hi :) 
Which version of magpie-base are you using?

**Comment by marcelklehr** [comment]
Unless you use socket functionality you shouldn't need to set a socketUrl and if the socket URL was wrong, you'd already have trouble in directLink mode as well.

**Comment by vini-macuch-silva** [comment]
I've made the jump to magpie v3 at some point last year (finally, yay). Funnily directLink submission has worked when I was using `socketUrl: 'http://localhost:4000/socket'`. Should I just remove that field altogether then if I'm not using it?

**Comment by marcelklehr** [comment]
What makes you think that socketUrl is the problem with prolific submissions?

**Comment by vini-macuch-silva** [comment]
To be fair, I was only guessing it had to do with that. Here's the config
file >
https://github.com/vini-macuch-silva/naturalness-rating/blob/master/src/magpie.config.js
< I'm not sure what else could be wrong, given that the directLink
submission works.

**Comment by marcelklehr** [comment]
When people on prolific access your experiment, what do they enter? Setting the serverUrl to anything with localhost is probably not going to work with prolific, because the prolific people need to access the server. localhost always means "the local computer", so for people coming from prolific, their browser will try to look for the magpie backend on their computer.

**Comment by vini-macuch-silva** [comment]
You're right, I was sending them directly to my local server, which makes
sense that they should not be able to access. I somehow thought as long as
the Docker image was running the server would be accessible. I guess I have
to actually host the magpie backend on an online server somewhere. That
should solve my problem, duh!

**Comment by vini-macuch-silva** [comment]
Though I have to say, it's still not clear to me how I can set up the
backend online other than using Heroku (which I have to pay to use). I have
a server I can use (and access using mucommander), just not sure how to
actually set up the backend there. This page >
https://magpie-experiments.org/02_using_the_server_app/01_installation/ <
only lists Heroku, docker, and local installation.

**Comment by x-ji** [comment]
Hi @vini-macuch-silva 👋 , I think we need to update the documentation (would be the best if we can have a single source of truth and sync that e.g. from the README). In the meanwhile the README at https://github.com/magpie-ea/magpie-backend/ should be up-to-date and document how to deploy on Gigalixir or Fly.io, two alternatives as Heroku is now no longer free. Could you give it a try and see if it works? Thanks 🙏 .

**Comment by vini-macuch-silva** [comment]
Hi @Xiang Ji ***@***.***> Thanks for that, I remember you sending me
something like this a while back, probably the issue back then was that I
was still using magpie 2.0 (or I just never came back to the issue). I'll
have a look and report back.

**Comment by vini-macuch-silva** [comment]
OK, so I've tried the gigalixir installation and I'm getting stuck at the
last step, when doing the `git push -u gigalixir master`. Am I correct in
just following the steps in a blank folder with a git repo in it (with a
remote on github, ofc)?

**Comment by vini-macuch-silva** [comment]
Never mind, I'm so stupid, ofc I need the backend files in the folder XD.
Problem solved, server up and running as it should! I'll report later once
I manage to get the data in from Prolific. Thanks for your help!

**Comment by vini-macuch-silva** [comment]
Right, so it's working as it should, data being submitted perfectly!
